### ISSUE TITLE
Why Nuxt Router Module?

### ISSUE THREAD

**Issue by InstanceOfMichael** [cretueusebiu/laravel-nuxt#33]
I felt like the way nuxt generates routes automatically by default was one of it's best features.

**Comment by cretueusebiu** [comment]
I like for example to have the `login`, `register` pages under an `auth/` folder but I still want the url to be `/login`.
I know you could add aliases or register custom routes, but since I've found [@nuxtjs/router](https://github.com/nuxt-community/router-module#readme), I'm just using it this way.

You can just remove it and still use the default router.
